mod 'zack/r10k'
mod 'puppetlabs/git'
mod 'puppetlabs/vcsrepo'
mod 'puppetlabs/inifile'
mod 'puppetlabs/concat'
mod 'puppetlabs/ruby'
mod 'puppetlabs/stdlib'
mod 'huskycode/vim'
mod 'maestrodev/wget'
mod 'CraigWatson1987/vmwaretools'
mod 'netrc', :git => 'https://github.com/benburkert/puppet-netrc.git'
mod 'herculesteam/augeasproviders_core'
mod 'herculesteam/augeasproviders_base'
mod 'herculesteam/augeasproviders_shellvar'
